import {
  LayoutDashboard,
  FolderKanban,
  Wand2,
  ShieldCheck,
  ClipboardCheck,
  Settings,
  Users,
  ScrollText,
  LayoutTemplate,
  Cog,
  LayoutPanelLeft,
  GraduationCap,
  Sparkles,
  Video,
  Megaphone,
  ShieldHalf,
  DollarSign,
  Vault,
  Package,
  Ticket,
  Network,
  GitPullRequest,
  DownloadCloud,
  Inbox,
} from "lucide-react";

export const userNav = [
  { label: "Dashboard", to: "/dashboard", icon: LayoutDashboard },
  { label: "Prompt Engine", to: "/tools/prompt-engine", icon: Wand2 },
  { label: "Prompt Vault", to: "/vault/access", icon: Vault },
  { label: "Migration Planner", to: "/migration-planner/assessments", icon: GitPullRequest },
  { label: "Resources/Learn", to: "/help", icon: GraduationCap },
  { label: "Settings", to: "/settings", icon: Settings },
];

export const projectNav = [
  { label: "Overview", to: "overview", icon: LayoutPanelLeft },
  { label: "Prompt Pack", to: "prompts", icon: Wand2 },
  { label: "Optimization Prompts", to: "optimize", icon: Sparkles },
  { label: "Security Review", to: "security", icon: ShieldCheck },
  { label: "QA Checklist", to: "qa", icon: ClipboardCheck },
];

export const adminNav = [
  { label: "Admin Dashboard", to: "/admin", icon: LayoutDashboard },
  { label: "Users", to: "/admin/users", icon: Users },
  { label: "CRM — Contacts", to: "/admin/crm", icon: Inbox },
  { label: "Projects", to: "/admin/projects", icon: FolderKanban },
  { label: "AI Usage Logs", to: "/admin/logs", icon: ScrollText },
  { label: "Templates", to: "/admin/templates", icon: LayoutTemplate },
  { label: "Videos", to: "/admin/videos", icon: Video },
  { label: "Marketing", to: "/admin/marketing", icon: Megaphone },
  { label: "Prompt Vault", to: "/admin/prompt-vault", icon: Vault },
  { label: "Agent Skills", to: "/admin/agent-skills", icon: Sparkles },
  { label: "Sales & Orders", to: "/admin/sales", icon: DollarSign },
  { label: "Migration Planner", to: "/admin/migration-planner", icon: GitPullRequest },
  { label: "Products & Downloads", to: "/admin/products", icon: Package },
  { label: "Download Logs", to: "/admin/download-logs", icon: DownloadCloud },
  { label: "Coupons", to: "/admin/coupons", icon: Ticket },
  { label: "Security", to: "/admin/security", icon: ShieldHalf },
  { label: "System Settings", to: "/admin/settings", icon: Cog },
  { label: "Visual Sitemap", to: "/admin/sitemap", icon: Network },
];