import { useEffect,useState } from "react";
import { useParams,useSearchParams,Link } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import LoadingState from "@/components/shared/LoadingState";
import ErrorState from "@/components/shared/ErrorState";
import ScanProgress from "@/components/migration/ScanProgress";
import MigrationPreview from "@/components/migration/MigrationPreview";
import ProjectActionBar from "@/components/migration/ProjectActionBar";
import useMigrationProject from "@/hooks/useMigrationProject";
import { trackEvent } from "@/lib/analytics";
export default function MigrationProject(){
 const {id}=useParams(),[params]=useSearchParams(),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const {data,loading,error,refresh}=useMigrationProject(id,true);
 const scan=async()=>{setBusy(true);setMessage("");try{await base44.functions.invoke("startMigrationScan",{project_id:id});await refresh()}catch(e){setMessage(e.response?.data?.error||e.message)}setBusy(false)};
 useEffect(()=>{if(params.get("start")==="1"&&data?.project?.scan_status==="draft"&&!busy)scan()},[data?.project?.scan_status]);
 useEffect(()=>{if(data?.entitled&&data.report?.status==="preview_ready"){base44.functions.invoke("generateMigrationReport",{project_id:id}).then(refresh)}},[data?.entitled,data?.report?.status,id]);
 const checkout=async(type,coupon_code="")=>{setBusy(true);setMessage("");try{const r=await base44.functions.invoke("migrationCheckout",{project_id:id,payment_type:type,coupon_code,redirect_url:`${window.location.origin}/migration-planner/projects/${id}?checkout=${type}`});if(r.data.already_unlocked){if(r.data.coupon_applied){trackEvent("migration_coupon_applied",{coupon_type:"moderator_full_report"});setMessage("Coupon applied. Your full migration plan is unlocked.")}await refresh();setBusy(false)}else window.location.href=r.data.checkout_url}catch(e){setMessage(e.response?.data?.error||e.message);setBusy(false)}};
 const consult=async()=>{try{const r=await base44.functions.invoke("recordMigrationConsultation",{project_id:id});window.open(r.data.booking_url,"_blank")}catch(e){setMessage(e.response?.data?.error||e.message)}};
 if(loading)return <LoadingState label="Loading assessment…"/>;if(error)return <ErrorState description={error}/>;const p=data.project;
 return <div className="max-w-5xl mx-auto space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm text-primary font-semibold">MIGRATION ASSESSMENT</p><h1 className="font-sora text-3xl font-bold">{p.application_name}</h1><p className="text-sm text-muted-foreground">{p.github_repository?`${p.github_owner}/${p.github_repository} · ${p.github_branch}`:"Authorized ZIP upload"}</p></div><Button asChild variant="outline"><Link to="/migration-planner/assessments">All assessments</Link></Button></div>{message&&<div className="rounded-xl bg-destructive/10 p-4 text-sm text-destructive">{message}</div>}{p.scan_status!=="completed"&&<ScanProgress project={p}/>} {p.scan_status==="failed"&&<Button onClick={scan} disabled={busy}>Retry scan</Button>} {data.report&&!data.entitled&&<MigrationPreview preview={data.report.preview_summary} onUnlock={coupon=>checkout("report",coupon)} loading={busy}/>} {data.entitled&&<div className="rounded-2xl border border-primary/30 bg-primary/5 p-6"><h2 className="font-sora text-2xl font-bold">Full migration plan unlocked</h2><p className="text-muted-foreground mt-1 mb-4">{data.report.status==="ready"?"Your complete report and quote are ready.":"Your complete report is being generated from the verified scan."}</p>{data.report.status==="ready"&&<div className="flex gap-2"><Button asChild><Link to={`/migration-planner/projects/${id}/report`}>View full report</Link></Button><Button asChild variant="outline"><Link to={`/migration-planner/projects/${id}/quote`}>View quote</Link></Button></div>}</div>}<ProjectActionBar busy={busy} onRescan={scan} onConsult={consult} onReview={()=>base44.functions.invoke("migrationAssessment",{action:"manual_review",project_id:id}).then(()=>setMessage("Manual quote review requested."))} onArchive={()=>base44.functions.invoke("migrationAssessment",{action:"archive",project_id:id}).then(()=>window.location.href="/migration-planner/assessments")}/></div>;
}