import { useCallback,useEffect,useState } from "react";
import { base44 } from "@/api/base44Client";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import LoadingState from "@/components/shared/LoadingState";
import AdminMigrationStats from "@/components/admin/migration/AdminMigrationStats";
import AdminProjectsTab from "@/components/admin/migration/AdminProjectsTab";
import AdminReportsTab from "@/components/admin/migration/AdminReportsTab";
import AdminQuotesTab from "@/components/admin/migration/AdminQuotesTab";
import AdminPaymentsTab from "@/components/admin/migration/AdminPaymentsTab";
import AdminPricingTab from "@/components/admin/migration/AdminPricingTab";
import AdminMigrationSettings from "@/components/admin/migration/AdminMigrationSettings";
import AdminQuoteLeadsTab from "@/components/admin/migration/AdminQuoteLeadsTab";
export default function AdminMigrationPlanner(){const [data,setData]=useState(null);const load=useCallback(()=>base44.functions.invoke("migrationAdmin",{action:"overview"}).then(r=>setData(r.data)),[]);useEffect(()=>{load()},[load]);if(!data)return <LoadingState label="Loading Migration Planner…"/>;return <div className="space-y-6"><div><p className="text-sm text-primary font-semibold">ADMIN</p><h1 className="font-sora text-3xl font-bold">Migration Planner</h1><p className="text-sm text-muted-foreground">Assessments, reports, quotes, payments, pricing, and settings.</p></div><AdminMigrationStats stats={data.stats}/><Tabs defaultValue="requests"><TabsList className="flex flex-wrap h-auto"><TabsTrigger value="requests">Quote Requests</TabsTrigger><TabsTrigger value="projects">Projects</TabsTrigger><TabsTrigger value="reports">Reports</TabsTrigger><TabsTrigger value="quotes">Quotes</TabsTrigger><TabsTrigger value="payments">Payments</TabsTrigger><TabsTrigger value="pricing">Pricing</TabsTrigger><TabsTrigger value="settings">Settings</TabsTrigger></TabsList><TabsContent value="requests"><AdminQuoteLeadsTab/></TabsContent><TabsContent value="projects"><AdminProjectsTab projects={data.projects} onRefresh={load}/></TabsContent><TabsContent value="reports"><AdminReportsTab reports={data.reports} onRefresh={load}/></TabsContent><TabsContent value="quotes"><AdminQuotesTab quotes={data.quotes} onRefresh={load}/></TabsContent><TabsContent value="payments"><AdminPaymentsTab payments={data.payments} onRefresh={load}/></TabsContent><TabsContent value="pricing"><AdminPricingTab rules={data.rules} onRefresh={load}/></TabsContent><TabsContent value="settings"><AdminMigrationSettings settings={data.settings} onRefresh={load}/></TabsContent></Tabs></div>;}